### ISSUE TITLE
FileNotFoundError: activate_this.py

### ISSUE THREAD

**Issue by ahxxm** [jmcantrell/vim-virtualenv#45]
The virtualenv is created using `python3 -m venv`, where python3(3.4.3) is installed by homebrew in OSX: It's build-in venv module does not automatically create `activate_this.py`. 

I then copied same file from other virtualenv, and found this activation file (might) could be generally used, could you add it as a backup plan for activating virtualenv?

here's the activate_this.py:

	"""By using execfile(this_file, dict(__file__=this_file)) you will
	activate this virtualenv environment.

	This can be used when you must use an existing Python interpreter, not
	the virtualenv bin/python
	"""

	try:
	    __file__
	except NameError:
	    raise AssertionError(
	        "You must run this like execfile('path/to/activate_this.py', dict(__file__='path/to/activate_this.py'))")
	import sys
	import os

	old_os_path = os.environ['PATH']
	os.environ['PATH'] = os.path.dirname(os.path.abspath(__file__)) + os.pathsep + old_os_path
	base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	if sys.platform == 'win32':
	    site_packages = os.path.join(base, 'Lib', 'site-packages')
	else:
	    site_packages = os.path.join(base, 'lib', 'python%s' % sys.version[:3], 'site-packages')
	prev_sys_path = list(sys.path)
	import site
	site.addsitedir(site_packages)
	sys.real_prefix = sys.prefix
	sys.prefix = base
	# Move the added items to the front of the path:
	new_sys_path = []
	for item in list(sys.path):
	    if item not in prev_sys_path:
	        new_sys_path.append(item)
	        sys.path.remove(item)
	sys.path[:0] = new_sys_path

**Comment by mlongval** [comment]
Same problem here. 

    Error detected while processing function virtualenv#activate: line   38:
    Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/Users/doc/Sync/config/vim/bundle/vim-virtualenv/autoload/pyvenv.py", line 9, in activate
        with open(activate) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/doc/Sync/src/python/emr_new/bin/activate_this.py'

Thanks for any help.

**Comment by tony** [comment]
See also https://github.com/klen/python-mode/issues/406

**Comment by romulocollopy** [comment]
fixed in #46

**Comment by ahxxm** [comment]
ah yes, my PR, and it's already merged...

**Comment by tony** [comment]
Thanks all.

We have a PR for python-mode's virtualenv also at https://github.com/klen/python-mode/pull/609.

That should cover us.

**Comment by elshaddae** [comment]
I still have this issue and my solution is to copy activate_this.py from the virtualenv. Any explanation about these merges I see here?
